Fix shader compilation
Errors:
0:27(12): error: cannot construct `mat3' from a matrix in GLSL 1.10
(GLSL 1.20 or GLSL ES 1.00 required)

and

0:8(15): error: no matching function for call to `texture2D(sampler2D, vec4)'

are fixed